# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-07-22 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='up_vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to=b''),
        ),
    ]
